export const PRODUCT_CATALOG = [
  {
    id: 1,
    name: "MacBook Air M2",
    category: "Laptop",
    price: 1199,
    description: "Ultra-thin and light laptop with Apple M2 chip, perfect for productivity and creative work",
    features: ["13.6-inch Retina display", "M2 chip", "Up to 18 hours battery life", "8GB RAM", "256GB SSD"],
    weight: "2.7 lbs",
    batteryLife: "18 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Students", "Professionals", "Creative work", "Travel"]
  },
  {
    id: 2,
    name: "Dell XPS 13",
    category: "Laptop",
    price: 999,
    description: "Premium Windows laptop with excellent build quality and performance",
    features: ["13.4-inch InfinityEdge display", "Intel Core i7", "16GB RAM", "512GB SSD", "Backlit keyboard"],
    weight: "2.8 lbs",
    batteryLife: "12 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Business users", "Developers", "Windows users", "Professional work"]
  },
  {
    id: 3,
    name: "Lenovo ThinkPad X1 Carbon",
    category: "Laptop",
    price: 1499,
    description: "Business-focused laptop with exceptional durability and security features",
    features: ["14-inch 4K display", "Intel Core i7", "16GB RAM", "1TB SSD", "Fingerprint reader"],
    weight: "2.5 lbs",
    batteryLife: "15 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Business professionals", "IT professionals", "Security-conscious users", "Corporate environments"]
  },
  {
    id: 4,
    name: "ASUS ROG Zephyrus G14",
    category: "Gaming Laptop",
    price: 1299,
    description: "Powerful gaming laptop with AMD Ryzen processor and dedicated graphics",
    features: ["14-inch 144Hz display", "AMD Ryzen 9", "RTX 4060", "16GB RAM", "1TB SSD"],
    weight: "3.5 lbs",
    batteryLife: "8 hours",
    performance: "Very High",
    portability: "Good",
    bestFor: ["Gamers", "Content creators", "Video editing", "3D modeling"]
  },
  {
    id: 5,
    name: "HP Pavilion 15",
    category: "Laptop",
    price: 699,
    description: "Affordable laptop with good performance for everyday tasks",
    features: ["15.6-inch Full HD display", "Intel Core i5", "8GB RAM", "256GB SSD", "Numeric keypad"],
    weight: "3.8 lbs",
    batteryLife: "7 hours",
    performance: "Medium",
    portability: "Good",
    bestFor: ["Students", "Home users", "Basic productivity", "Budget-conscious buyers"]
  },
  {
    id: 6,
    name: "Microsoft Surface Laptop 5",
    category: "Laptop",
    price: 1099,
    description: "Premium Windows laptop with excellent touch screen and build quality",
    features: ["13.5-inch PixelSense display", "Intel Core i7", "16GB RAM", "512GB SSD", "Touch screen"],
    weight: "2.9 lbs",
    batteryLife: "14 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Creative professionals", "Students", "Touch screen enthusiasts", "Windows ecosystem users"]
  },
  {
    id: 7,
    name: "Acer Swift 3",
    category: "Laptop",
    price: 599,
    description: "Lightweight and affordable laptop with good battery life",
    features: ["14-inch Full HD display", "AMD Ryzen 5", "8GB RAM", "256GB SSD", "Backlit keyboard"],
    weight: "2.6 lbs",
    batteryLife: "11 hours",
    performance: "Medium",
    portability: "Excellent",
    bestFor: ["Students", "Travelers", "Budget buyers", "Light productivity"]
  },
  {
    id: 8,
    name: "Razer Blade 15",
    category: "Gaming Laptop",
    price: 1999,
    description: "Premium gaming laptop with high-end graphics and RGB lighting",
    features: ["15.6-inch 240Hz display", "Intel Core i7", "RTX 4070", "16GB RAM", "1TB SSD"],
    weight: "4.4 lbs",
    batteryLife: "6 hours",
    performance: "Very High",
    portability: "Fair",
    bestFor: ["Serious gamers", "Streamers", "Content creators", "VR development"]
  },
  {
    id: 9,
    name: "Google Pixelbook Go",
    category: "Chromebook",
    price: 649,
    description: "Premium Chromebook with excellent battery life and lightweight design",
    features: ["13.3-inch Full HD display", "Intel Core m3", "8GB RAM", "64GB eMMC", "Backlit keyboard"],
    weight: "2.3 lbs",
    batteryLife: "12 hours",
    performance: "Medium",
    portability: "Excellent",
    bestFor: ["Students", "Web browsing", "Google ecosystem users", "Light productivity"]
  },
  {
    id: 10,
    name: "MSI GS66 Stealth",
    category: "Gaming Laptop",
    price: 1599,
    description: "Sleek gaming laptop with powerful performance in a thin form factor",
    features: ["15.6-inch 144Hz display", "Intel Core i7", "RTX 3060", "16GB RAM", "512GB SSD"],
    weight: "4.6 lbs",
    batteryLife: "7 hours",
    performance: "High",
    portability: "Good",
    bestFor: ["Gamers", "Content creators", "Students", "Portable gaming"]
  },
  {
    id: 11,
    name: "MacBook Pro 14 M3",
    category: "Professional Laptop",
    price: 1999,
    description: "Professional-grade laptop with M3 chip for demanding creative and development work",
    features: ["14.2-inch Liquid Retina XDR display", "M3 Pro chip", "18GB RAM", "512GB SSD", "ProMotion 120Hz"],
    weight: "3.5 lbs",
    batteryLife: "22 hours",
    performance: "Very High",
    portability: "Excellent",
    bestFor: ["Creative professionals", "Developers", "Video editors", "3D artists", "Power users"]
  },
  {
    id: 12,
    name: "Dell Precision 5570",
    category: "Workstation",
    price: 2499,
    description: "Mobile workstation with professional-grade graphics for CAD and 3D work",
    features: ["15.6-inch 4K display", "Intel Core i7", "NVIDIA RTX A1000", "32GB RAM", "1TB SSD"],
    weight: "4.2 lbs",
    batteryLife: "10 hours",
    performance: "Very High",
    portability: "Good",
    bestFor: ["Engineers", "Architects", "CAD professionals", "3D modeling", "Data scientists"]
  },
  {
    id: 13,
    name: "Lenovo Yoga 9i",
    category: "2-in-1 Laptop",
    price: 1299,
    description: "Premium 2-in-1 convertible laptop with 360-degree hinge and stylus support",
    features: ["14-inch 4K touch display", "Intel Core i7", "16GB RAM", "512GB SSD", "360-degree hinge"],
    weight: "3.1 lbs",
    batteryLife: "13 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Creative professionals", "Students", "Note-taking", "Drawing", "Presentations"]
  },
  {
    id: 14,
    name: "ASUS ZenBook 14",
    category: "Ultrabook",
    price: 899,
    description: "Ultra-thin and light laptop with innovative NumberPad and premium design",
    features: ["14-inch Full HD display", "Intel Core i7", "16GB RAM", "512GB SSD", "NumberPad"],
    weight: "2.6 lbs",
    batteryLife: "12 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Business professionals", "Students", "Travelers", "Light productivity", "Style-conscious users"]
  },
  {
    id: 15,
    name: "HP Envy 13",
    category: "Premium Laptop",
    price: 999,
    description: "Premium laptop with Bang & Olufsen audio and sleek aluminum design",
    features: ["13.3-inch 4K display", "Intel Core i7", "16GB RAM", "512GB SSD", "Bang & Olufsen audio"],
    weight: "2.9 lbs",
    batteryLife: "11 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Music producers", "Content creators", "Business users", "Media consumption", "Premium buyers"]
  },
  {
    id: 16,
    name: "Acer Predator Helios 300",
    category: "Gaming Laptop",
    price: 1099,
    description: "Affordable gaming laptop with excellent performance and RGB keyboard",
    features: ["15.6-inch 144Hz display", "Intel Core i7", "RTX 3060", "16GB RAM", "512GB SSD"],
    weight: "5.1 lbs",
    batteryLife: "6 hours",
    performance: "High",
    portability: "Fair",
    bestFor: ["Gamers", "Budget gaming", "Students", "Content creation", "VR gaming"]
  },
  {
    id: 17,
    name: "Microsoft Surface Pro 9",
    category: "Tablet/Laptop Hybrid",
    price: 1399,
    description: "Versatile 2-in-1 device that works as both tablet and laptop",
    features: ["13-inch PixelSense display", "Intel Core i7", "16GB RAM", "256GB SSD", "Detachable keyboard"],
    weight: "1.9 lbs",
    batteryLife: "15 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Artists", "Students", "Business travelers", "Note-taking", "Drawing", "Presentations"]
  },
  {
    id: 18,
    name: "Dell Alienware x14",
    category: "Gaming Laptop",
    price: 1799,
    description: "Ultra-thin gaming laptop with premium build and RGB lighting",
    features: ["14-inch 144Hz display", "Intel Core i7", "RTX 4060", "16GB RAM", "512GB SSD"],
    weight: "3.8 lbs",
    batteryLife: "8 hours",
    performance: "Very High",
    portability: "Good",
    bestFor: ["Gamers", "Content creators", "Streamers", "Portable gaming", "Premium gaming"]
  },
  {
    id: 19,
    name: "Lenovo IdeaPad 5",
    category: "Budget Laptop",
    price: 549,
    description: "Affordable laptop with good performance for everyday computing",
    features: ["15.6-inch Full HD display", "AMD Ryzen 5", "8GB RAM", "256GB SSD", "Backlit keyboard"],
    weight: "3.6 lbs",
    batteryLife: "9 hours",
    performance: "Medium",
    portability: "Good",
    bestFor: ["Students", "Home users", "Basic productivity", "Web browsing", "Budget buyers"]
  },
  {
    id: 20,
    name: "Apple MacBook Air M3",
    category: "Premium Laptop",
    price: 1099,
    description: "Latest MacBook Air with M3 chip, perfect balance of performance and portability",
    features: ["13.6-inch Liquid Retina display", "M3 chip", "8GB RAM", "256GB SSD", "MagSafe charging"],
    weight: "2.7 lbs",
    batteryLife: "18 hours",
    performance: "High",
    portability: "Excellent",
    bestFor: ["Students", "Professionals", "Creative work", "Travel", "Apple ecosystem users"]
  },
  {
    id: 21,
    name: "Lenovo Chromebook Flex 5",
    category: "Student Chromebook",
    price: 399,
    description: "Affordable Chromebook with excellent battery life, perfect for students and online learning",
    features: ["13.3-inch Full HD touch display", "Intel Core i3", "4GB RAM", "64GB eMMC", "360-degree hinge"],
    weight: "2.9 lbs",
    batteryLife: "13 hours",
    performance: "Medium",
    portability: "Excellent",
    bestFor: ["Students", "Online learning", "Web browsing", "Note-taking", "Budget-conscious buyers"]
  },
  {
    id: 22,
    name: "Acer Aspire 5",
    category: "Budget Student Laptop",
    price: 449,
    description: "Excellent value laptop with long battery life, perfect for students on a tight budget",
    features: ["15.6-inch Full HD display", "AMD Ryzen 3", "8GB RAM", "256GB SSD", "Backlit keyboard"],
    weight: "3.9 lbs",
    batteryLife: "11 hours",
    performance: "Medium",
    portability: "Good",
    bestFor: ["Students", "Budget buyers", "Basic productivity", "Web browsing", "Online classes"]
  },
  {
    id: 23,
    name: "HP 14-inch Chromebook",
    category: "Student Chromebook",
    price: 329,
    description: "Ultra-affordable Chromebook with impressive battery life for students",
    features: ["14-inch HD display", "Intel Celeron", "4GB RAM", "32GB eMMC", "Lightweight design"],
    weight: "3.2 lbs",
    batteryLife: "12 hours",
    performance: "Low",
    portability: "Excellent",
    bestFor: ["Students", "Online learning", "Web browsing", "Email", "Ultra-budget buyers"]
  },
  {
    id: 24,
    name: "Dell Inspiron 15 3000",
    category: "Budget Student Laptop",
    price: 479,
    description: "Reliable budget laptop with good battery life for student needs",
    features: ["15.6-inch Full HD display", "Intel Core i3", "8GB RAM", "256GB SSD", "Numeric keypad"],
    weight: "4.1 lbs",
    batteryLife: "10 hours",
    performance: "Medium",
    portability: "Good",
    bestFor: ["Students", "Basic productivity", "Web browsing", "Online classes", "Budget-conscious users"]
  },
  {
    id: 25,
    name: "ASUS VivoBook 15",
    category: "Student Laptop",
    price: 499,
    description: "Lightweight student laptop with excellent battery life and modern design",
    features: ["15.6-inch Full HD display", "AMD Ryzen 5", "8GB RAM", "256GB SSD", "Ergonomic keyboard"],
    weight: "3.5 lbs",
    batteryLife: "12 hours",
    performance: "Medium",
    portability: "Excellent",
    bestFor: ["Students", "Light productivity", "Web browsing", "Note-taking", "Portable computing"]
  }
];
